version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  build-tags:
    - nowebp

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gosec
    - bodyclose
    - nilerr

  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    govet:
      enable-all: true

    misspell:
      locale: US

    gosec:
      excludes:
        - G301 # Expect directory permissions to be 0750 or less
        - G306 # Expect file permissions to be 0600 or less
        - G703 # Potential tainted input to MkdirAll (false positive after validation)

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck # Allow ignoring errors in tests for brevity
        - gosec # Allow test code patterns
        - govet # Relax field alignment in test structs

    # Exclude example files from strict checking
    - path: example_test\.go
      linters:
        - errcheck
        - gosec
